language: generic

# CI only works on Linux or macOS, Unity only works on Windows or macOS
# Therefore must use macOS 
os: osx

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change
    
rvm:
- 2.2

before_install:
- chmod a+x ./TravisBuildScripts/install.sh
- chmod a+x ./TravisBuildScripts/build.sh
    
install:
- sudo -E sh ./TravisBuildScripts/install.sh

script:
- sudo -E sh ./TravisBuildScripts/build.sh

# Set project name
env:
  global:
  - UNITYCI_PROJECT_NAME="UnityProject"
